DROP DATABASE IF EXISTS gim;
CREATE DATABASE IF NOT EXISTS gim; #Crea la libreria si es que no exite
USE gim; #uso de la libreria

CREATE TABLE IF NOT EXISTS rooms(
  `room` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `description` TEXT
)CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS types_payments(
  `type_payment` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `cost`DOUBLE NOT NULL,
  `description` TEXT
);

CREATE TABLE IF NOT EXISTS coachs (
`coach` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`name`  VARCHAR(60) NOT NULL,
`mail` VARCHAR(60) NOT NULL,
`phone` VARCHAR(20) NOT NULL,
`gender` ENUM('M','F','NP') NOT NULL,
`address` VARCHAR(80) NOT NULL,
`PHOTO` VARCHAR(100),
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`active` TINYINT(1) NOT NULL DEFAULT '1'
)CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS customers (
  `customer` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name`  VARCHAR(60) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `birthdate` date DEFAULT NULL,
  `phone` VARCHAR(20) DEFAULT NULL,
  `gender` ENUM('M','F','NP') DEFAULT NULL,
  `address` VARCHAR(80) DEFAULT NULL,
  `PHOTO` VARCHAR(100),
  `active` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `email` (`email`)
)CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS clients(
  `clientid` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `customer` INT UNSIGNED NOT NULL,
  `type_payment` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `start` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `finish` TIMESTAMP NOT NULL,
  `active` INT(1) NOT NULL DEFAULT '1',
  FOREIGN KEY (customer) REFERENCES customers(customer),
  FOREIGN KEY (type_payment) REFERENCES types_payments(type_payment)
);

CREATE TABLE IF NOT EXISTS classes (
  `class` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `room` INT UNSIGNED NOT NULL,
  `coach` INT UNSIGNED NOT NULL,
  `date` DATE NOT NULL,
  `finish` TIME NOT NULL,
  `start` TIME NOT NULL,
  FOREIGN KEY (coach) REFERENCES coachs(coach),
  FOREIGN KEY (room) REFERENCES rooms(room)
)CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS assists(
`assistance` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`class` INT UNSIGNED NOT NULL,
`clientid` INT UNSIGNED NOT NULL,
`start` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`finish` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`active` INT(1) NOT NULL DEFAULT '1',
FOREIGN KEY (clientid) REFERENCES clients(clientid),
FOREIGN KEY (class) REFERENCES classes(class)
)CHARSET=utf8mb4;
