DROP DATABASE IF EXISTS sell;
CREATE DATABASE IF NOT EXISTS sell;
USE sell;


CREATE TABLE IF NOT EXISTS `type_persons`(
  `type_person_id` INTEGER UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(250) NOT NULL UNIQUE KEY
)DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS `persons`(
  `person_id` INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `gender` ENUM('M','F','NP') NOT NULL,
  `email` varchar(100) NOT NULL UNIQUE KEY,
  `cell_phone_number` VARCHAR(20) UNIQUE KEY,
  `birthdate` DATETIME,
  `type_person_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` TINYINT(1) NOT NULL DEFAULT '1',
  FOREIGN KEY (type_person_id) REFERENCES type_persons(type_person_id)
)DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `users`(
  `user_id` INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `person_id` INT UNSIGNED NOT NULL UNIQUE KEY,
  `user_name` VARCHAR(250) NOT NULL,
  `password`  VARCHAR(250) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` TINYINT(1) NOT NULL DEFAULT '1',
  FOREIGN KEY (person_id) REFERENCES persons(person_id)
)DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `type_products`(
  `type_product_id` INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `type_product_name` VARCHAR(250) NOT NULL UNIQUE KEY,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` TINYINT(1) NOT NULL DEFAULT '1'
)DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `products`(
  `product_id` INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `type_product_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `quantity` INT UNSIGNED NOT NULL DEFAULT '0',
  `cover_url` VARCHAR(500) DEFAULT NULL,
  `price` DOUBLE(6,2) DEFAULT NULL,
  `sellable` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` TINYINT(1) NOT NULL DEFAULT '1',
  `description` text,
  FOREIGN KEY (type_product_id) REFERENCES type_products(type_product_id)
)DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `transactions` (
  `transaction_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `product_id` int(10) unsigned NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `quantity` int(10) unsigned NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`transaction_id`),
  FOREIGN KEY (`product_id`) REFERENCES `products`(`product_id`),
  FOREIGN KEY (`user_id`) REFERENCES `users`(`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
